# Generated by Django 3.2.4 on 2021-06-13 23:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.FloatField()),
                ('valoresNegociables', models.FloatField()),
                ('deudoresPorVenta', models.FloatField()),
                ('deudoresVarios', models.FloatField()),
                ('impuestosPorRecuperar', models.FloatField()),
                ('cuentaPorPagar', models.FloatField()),
                ('proviciones', models.FloatField()),
                ('retenciones', models.FloatField()),
                ('convenioConInstituciones', models.FloatField()),
                ('otros', models.FloatField()),
                ('mueblesUtiles', models.FloatField()),
                ('maquinariaEquipoOficina', models.FloatField()),
                ('otrosActivosFijos', models.FloatField()),
                ('equipoTransporte', models.FloatField()),
                ('acredoresHipotecarios', models.FloatField()),
                ('programasComputacionales', models.FloatField()),
                ('otros2', models.FloatField()),
                ('amortizaciones', models.FloatField()),
                ('capitalSocial', models.FloatField()),
                ('utilidadesRetenidas', models.FloatField()),
                ('fechaCreacion', models.DateField(default=datetime.datetime.now)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
