# Generated by Django 3.2.4 on 2021-06-14 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancegeneral',
            old_name='proviciones',
            new_name='provedores',
        ),
    ]
