# Generated by Django 3.2.3 on 2021-06-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rename_proviciones_balancegeneral_provedores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancegeneral',
            name='acredoresHipotecarios',
            field=models.FloatField(default=0),
        ),
    ]
