# Generated by Django 3.2.3 on 2021-06-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_balancegeneral_acredoreshipotecarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancegeneral',
            name='amortizaciones',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='capitalSocial',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='convenioConInstituciones',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='cuentaPorPagar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='deudoresPorVenta',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='deudoresVarios',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='disponible',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='equipoTransporte',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='impuestosPorRecuperar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='maquinariaEquipoOficina',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='mueblesUtiles',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='otros',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='otros2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='otrosActivosFijos',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='programasComputacionales',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='provedores',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='retenciones',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='utilidadesRetenidas',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='valoresNegociables',
            field=models.FloatField(default=0),
        ),
    ]
