# Generated by Django 3.2.3 on 2021-06-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_estadoresultados'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('salario', models.FloatField(default=0)),
                ('descripcion', models.CharField(max_length=60)),
            ],
        ),
    ]
