# Generated by Django 3.2.3 on 2021-06-15 02:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_tipoempleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ap_paterno', models.CharField(max_length=40)),
                ('ap_materno', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('fechaCreacion', models.DateField(default=datetime.datetime.now)),
                ('horas', models.IntegerField()),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.tipoempleado')),
            ],
        ),
    ]
